
env:
  - MIDGARD_TEST_CONFIGURATION_FILE=test_SQLITE.conf
  - MIDGARD_TEST_CONFIGURATION_FILE=test_MYSQL.conf
  - MIDGARD_TEST_CONFIGURATION_FILE=test_POSTGRESQL.conf

before_script:
  - ./travis_midgard.sh

script: sh -c "cd tests/GIR&&python runalltests.py" 

notifications:
    irc: "irc.freenode.org#midgard"
