/* midgard_config.h generated by valac 0.9.7.65-335d, the Vala compiler, do not modify */


#ifndef __MIDGARD_CONFIG_H__
#define __MIDGARD_CONFIG_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define MIDGARD_TYPE_CONFIG (midgard_config_get_type ())
#define MIDGARD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_TYPE_CONFIG, MidgardConfig))
#define MIDGARD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_TYPE_CONFIG, MidgardConfigClass))
#define MIDGARD_IS_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_TYPE_CONFIG))
#define MIDGARD_IS_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_TYPE_CONFIG))
#define MIDGARD_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_TYPE_CONFIG, MidgardConfigClass))

typedef struct _MidgardConfig MidgardConfig;
typedef struct _MidgardConfigClass MidgardConfigClass;
typedef struct _MidgardConfigPrivate MidgardConfigPrivate;

struct _MidgardConfig {
	GObject parent_instance;
	MidgardConfigPrivate * priv;
};

struct _MidgardConfigClass {
	GObjectClass parent_class;
};


GType midgard_config_get_type (void) G_GNUC_CONST;
gboolean midgard_config_read_file (MidgardConfig* self, const char* name, gboolean user, GError** error);
MidgardConfig* midgard_config_copy (MidgardConfig* self, MidgardConfig* src);
MidgardConfig* midgard_config_new (void);
MidgardConfig* midgard_config_construct (GType object_type);
const char* midgard_config_get_authtype (MidgardConfig* self);
void midgard_config_set_authtype (MidgardConfig* self, const char* value);
const char* midgard_config_get_dbname (MidgardConfig* self);
void midgard_config_set_dbname (MidgardConfig* self, const char* value);
const char* midgard_config_get_dbpass (MidgardConfig* self);
void midgard_config_set_dbpass (MidgardConfig* self, const char* value);
const char* midgard_config_get_dbtype (MidgardConfig* self);
void midgard_config_set_dbtype (MidgardConfig* self, const char* value);
const char* midgard_config_get_dbuser (MidgardConfig* self);
void midgard_config_set_dbuser (MidgardConfig* self, const char* value);
const char* midgard_config_get_host (MidgardConfig* self);
void midgard_config_set_host (MidgardConfig* self, const char* value);
const char* midgard_config_get_logfilename (MidgardConfig* self);
void midgard_config_set_logfilename (MidgardConfig* self, const char* value);
const char* midgard_config_get_loglevel (MidgardConfig* self);
void midgard_config_set_loglevel (MidgardConfig* self, const char* value);
const char* midgard_config_get_midgardpassword (MidgardConfig* self);
void midgard_config_set_midgardpassword (MidgardConfig* self, const char* value);
const char* midgard_config_get_midgardusername (MidgardConfig* self);
void midgard_config_set_midgardusername (MidgardConfig* self, const char* value);
guint midgard_config_get_port (MidgardConfig* self);
void midgard_config_set_port (MidgardConfig* self, guint value);
const char* midgard_config_get_sharedir (MidgardConfig* self);
void midgard_config_set_sharedir (MidgardConfig* self, const char* value);
const char* midgard_config_get_vardir (MidgardConfig* self);
void midgard_config_set_vardir (MidgardConfig* self, const char* value);
const char* midgard_config_get_blobdir (MidgardConfig* self);
void midgard_config_set_blobdir (MidgardConfig* self, const char* value);
const char* midgard_config_get_cachedir (MidgardConfig* self);
void midgard_config_set_cachedir (MidgardConfig* self, const char* value);
const char* midgard_config_get_dbdir (MidgardConfig* self);
void midgard_config_set_dbdir (MidgardConfig* self, const char* value);
gboolean midgard_config_get_tablecreate (MidgardConfig* self);
void midgard_config_set_tablecreate (MidgardConfig* self, gboolean value);
gboolean midgard_config_get_tableupdate (MidgardConfig* self);
void midgard_config_set_tableupdate (MidgardConfig* self, gboolean value);
gboolean midgard_config_get_testunit (MidgardConfig* self);
void midgard_config_set_testunit (MidgardConfig* self, gboolean value);


G_END_DECLS

#endif
