/* midgard3.h generated by valac 0.9.7.109-f873e, the Vala compiler, do not modify */


#ifndef ________SRC_CORE_MIDGARD3_H__
#define ________SRC_CORE_MIDGARD3_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define MIDGARD_CR_TYPE_CONFIG (midgard_cr_config_get_type ())
#define MIDGARD_CR_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_CONFIG, MidgardCRConfig))
#define MIDGARD_CR_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_CONFIG, MidgardCRConfigClass))
#define MIDGARD_CR_IS_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_CONFIG))
#define MIDGARD_CR_IS_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_CONFIG))
#define MIDGARD_CR_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_CONFIG, MidgardCRConfigClass))

typedef struct _MidgardCRConfig MidgardCRConfig;
typedef struct _MidgardCRConfigClass MidgardCRConfigClass;
typedef struct _MidgardCRConfigPrivate MidgardCRConfigPrivate;

#define MIDGARD_CR_TYPE_EXECUTABLE (midgard_cr_executable_get_type ())
#define MIDGARD_CR_EXECUTABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_EXECUTABLE, MidgardCRExecutable))
#define MIDGARD_CR_IS_EXECUTABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_EXECUTABLE))
#define MIDGARD_CR_EXECUTABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_EXECUTABLE, MidgardCRExecutableIface))

typedef struct _MidgardCRExecutable MidgardCRExecutable;
typedef struct _MidgardCRExecutableIface MidgardCRExecutableIface;

#define MIDGARD_CR_TYPE_NAMESPACE_MANAGER (midgard_cr_namespace_manager_get_type ())
#define MIDGARD_CR_NAMESPACE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_NAMESPACE_MANAGER, MidgardCRNamespaceManager))
#define MIDGARD_CR_IS_NAMESPACE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_NAMESPACE_MANAGER))
#define MIDGARD_CR_NAMESPACE_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_NAMESPACE_MANAGER, MidgardCRNamespaceManagerIface))

typedef struct _MidgardCRNamespaceManager MidgardCRNamespaceManager;
typedef struct _MidgardCRNamespaceManagerIface MidgardCRNamespaceManagerIface;

#define MIDGARD_CR_TYPE_PROFILER (midgard_cr_profiler_get_type ())
#define MIDGARD_CR_PROFILER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_PROFILER, MidgardCRProfiler))
#define MIDGARD_CR_IS_PROFILER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_PROFILER))
#define MIDGARD_CR_PROFILER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_PROFILER, MidgardCRProfilerIface))

typedef struct _MidgardCRProfiler MidgardCRProfiler;
typedef struct _MidgardCRProfilerIface MidgardCRProfilerIface;

#define MIDGARD_CR_TYPE_QUERY_CONSTRAINT_SIMPLE (midgard_cr_query_constraint_simple_get_type ())
#define MIDGARD_CR_QUERY_CONSTRAINT_SIMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT_SIMPLE, MidgardCRQueryConstraintSimple))
#define MIDGARD_CR_IS_QUERY_CONSTRAINT_SIMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT_SIMPLE))
#define MIDGARD_CR_QUERY_CONSTRAINT_SIMPLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT_SIMPLE, MidgardCRQueryConstraintSimpleIface))

typedef struct _MidgardCRQueryConstraintSimple MidgardCRQueryConstraintSimple;
typedef struct _MidgardCRQueryConstraintSimpleIface MidgardCRQueryConstraintSimpleIface;

#define MIDGARD_CR_TYPE_QUERY_STORAGE (midgard_cr_query_storage_get_type ())
#define MIDGARD_CR_QUERY_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_STORAGE, MidgardCRQueryStorage))
#define MIDGARD_CR_IS_QUERY_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_STORAGE))
#define MIDGARD_CR_QUERY_STORAGE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_STORAGE, MidgardCRQueryStorageIface))

typedef struct _MidgardCRQueryStorage MidgardCRQueryStorage;
typedef struct _MidgardCRQueryStorageIface MidgardCRQueryStorageIface;

#define MIDGARD_CR_TYPE_QUERY_CONSTRAINT (midgard_cr_query_constraint_get_type ())
#define MIDGARD_CR_QUERY_CONSTRAINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT, MidgardCRQueryConstraint))
#define MIDGARD_CR_IS_QUERY_CONSTRAINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT))
#define MIDGARD_CR_QUERY_CONSTRAINT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT, MidgardCRQueryConstraintIface))

typedef struct _MidgardCRQueryConstraint MidgardCRQueryConstraint;
typedef struct _MidgardCRQueryConstraintIface MidgardCRQueryConstraintIface;

#define MIDGARD_CR_TYPE_QUERY_VALUE_HOLDER (midgard_cr_query_value_holder_get_type ())
#define MIDGARD_CR_QUERY_VALUE_HOLDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_VALUE_HOLDER, MidgardCRQueryValueHolder))
#define MIDGARD_CR_IS_QUERY_VALUE_HOLDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_VALUE_HOLDER))
#define MIDGARD_CR_QUERY_VALUE_HOLDER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_VALUE_HOLDER, MidgardCRQueryValueHolderIface))

typedef struct _MidgardCRQueryValueHolder MidgardCRQueryValueHolder;
typedef struct _MidgardCRQueryValueHolderIface MidgardCRQueryValueHolderIface;

#define MIDGARD_CR_TYPE_QUERY_PROPERTY (midgard_cr_query_property_get_type ())
#define MIDGARD_CR_QUERY_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_PROPERTY, MidgardCRQueryProperty))
#define MIDGARD_CR_QUERY_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_QUERY_PROPERTY, MidgardCRQueryPropertyClass))
#define MIDGARD_CR_IS_QUERY_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_PROPERTY))
#define MIDGARD_CR_IS_QUERY_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_QUERY_PROPERTY))
#define MIDGARD_CR_QUERY_PROPERTY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_QUERY_PROPERTY, MidgardCRQueryPropertyClass))

typedef struct _MidgardCRQueryProperty MidgardCRQueryProperty;
typedef struct _MidgardCRQueryPropertyClass MidgardCRQueryPropertyClass;

#define MIDGARD_CR_TYPE_QUERY_CONSTRAINT_GROUP (midgard_cr_query_constraint_group_get_type ())
#define MIDGARD_CR_QUERY_CONSTRAINT_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT_GROUP, MidgardCRQueryConstraintGroup))
#define MIDGARD_CR_IS_QUERY_CONSTRAINT_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT_GROUP))
#define MIDGARD_CR_QUERY_CONSTRAINT_GROUP_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_CONSTRAINT_GROUP, MidgardCRQueryConstraintGroupIface))

typedef struct _MidgardCRQueryConstraintGroup MidgardCRQueryConstraintGroup;
typedef struct _MidgardCRQueryConstraintGroupIface MidgardCRQueryConstraintGroupIface;

#define MIDGARD_CR_TYPE_QUERY_VALUE (midgard_cr_query_value_get_type ())
#define MIDGARD_CR_QUERY_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_VALUE, MidgardCRQueryValue))
#define MIDGARD_CR_QUERY_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_QUERY_VALUE, MidgardCRQueryValueClass))
#define MIDGARD_CR_IS_QUERY_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_VALUE))
#define MIDGARD_CR_IS_QUERY_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_QUERY_VALUE))
#define MIDGARD_CR_QUERY_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_QUERY_VALUE, MidgardCRQueryValueClass))

typedef struct _MidgardCRQueryValue MidgardCRQueryValue;
typedef struct _MidgardCRQueryValueClass MidgardCRQueryValueClass;
typedef struct _MidgardCRQueryValuePrivate MidgardCRQueryValuePrivate;
typedef struct _MidgardCRQueryPropertyPrivate MidgardCRQueryPropertyPrivate;

#define MIDGARD_CR_TYPE_QUERY_EXECUTOR (midgard_cr_query_executor_get_type ())
#define MIDGARD_CR_QUERY_EXECUTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_EXECUTOR, MidgardCRQueryExecutor))
#define MIDGARD_CR_IS_QUERY_EXECUTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_EXECUTOR))
#define MIDGARD_CR_QUERY_EXECUTOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_EXECUTOR, MidgardCRQueryExecutorIface))

typedef struct _MidgardCRQueryExecutor MidgardCRQueryExecutor;
typedef struct _MidgardCRQueryExecutorIface MidgardCRQueryExecutorIface;

#define MIDGARD_CR_TYPE_QUERY_SELECT (midgard_cr_query_select_get_type ())
#define MIDGARD_CR_QUERY_SELECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_SELECT, MidgardCRQuerySelect))
#define MIDGARD_CR_IS_QUERY_SELECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_SELECT))
#define MIDGARD_CR_QUERY_SELECT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_SELECT, MidgardCRQuerySelectIface))

typedef struct _MidgardCRQuerySelect MidgardCRQuerySelect;
typedef struct _MidgardCRQuerySelectIface MidgardCRQuerySelectIface;

#define MIDGARD_CR_TYPE_STORABLE (midgard_cr_storable_get_type ())
#define MIDGARD_CR_STORABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORABLE, MidgardCRStorable))
#define MIDGARD_CR_IS_STORABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORABLE))
#define MIDGARD_CR_STORABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORABLE, MidgardCRStorableIface))

typedef struct _MidgardCRStorable MidgardCRStorable;
typedef struct _MidgardCRStorableIface MidgardCRStorableIface;

#define MIDGARD_CR_TYPE_QUERY_DATA (midgard_cr_query_data_get_type ())
#define MIDGARD_CR_QUERY_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_DATA, MidgardCRQueryData))
#define MIDGARD_CR_IS_QUERY_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_DATA))
#define MIDGARD_CR_QUERY_DATA_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_DATA, MidgardCRQueryDataIface))

typedef struct _MidgardCRQueryData MidgardCRQueryData;
typedef struct _MidgardCRQueryDataIface MidgardCRQueryDataIface;

#define MIDGARD_CR_TYPE_MODEL_REFLECTOR (midgard_cr_model_reflector_get_type ())
#define MIDGARD_CR_MODEL_REFLECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_MODEL_REFLECTOR, MidgardCRModelReflector))
#define MIDGARD_CR_IS_MODEL_REFLECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_MODEL_REFLECTOR))
#define MIDGARD_CR_MODEL_REFLECTOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_MODEL_REFLECTOR, MidgardCRModelReflectorIface))

typedef struct _MidgardCRModelReflector MidgardCRModelReflector;
typedef struct _MidgardCRModelReflectorIface MidgardCRModelReflectorIface;

#define MIDGARD_CR_TYPE_MODEL (midgard_cr_model_get_type ())
#define MIDGARD_CR_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_MODEL, MidgardCRModel))
#define MIDGARD_CR_IS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_MODEL))
#define MIDGARD_CR_MODEL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_MODEL, MidgardCRModelIface))

typedef struct _MidgardCRModel MidgardCRModel;
typedef struct _MidgardCRModelIface MidgardCRModelIface;

#define MIDGARD_CR_TYPE_MODEL_PROPERTY_REFLECTOR (midgard_cr_model_property_reflector_get_type ())
#define MIDGARD_CR_MODEL_PROPERTY_REFLECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_MODEL_PROPERTY_REFLECTOR, MidgardCRModelPropertyReflector))
#define MIDGARD_CR_IS_MODEL_PROPERTY_REFLECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_MODEL_PROPERTY_REFLECTOR))
#define MIDGARD_CR_MODEL_PROPERTY_REFLECTOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_MODEL_PROPERTY_REFLECTOR, MidgardCRModelPropertyReflectorIface))

typedef struct _MidgardCRModelPropertyReflector MidgardCRModelPropertyReflector;
typedef struct _MidgardCRModelPropertyReflectorIface MidgardCRModelPropertyReflectorIface;

#define MIDGARD_CR_TYPE_MODEL_PROPERTY (midgard_cr_model_property_get_type ())
#define MIDGARD_CR_MODEL_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_MODEL_PROPERTY, MidgardCRModelProperty))
#define MIDGARD_CR_IS_MODEL_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_MODEL_PROPERTY))
#define MIDGARD_CR_MODEL_PROPERTY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_MODEL_PROPERTY, MidgardCRModelPropertyIface))

typedef struct _MidgardCRModelProperty MidgardCRModelProperty;
typedef struct _MidgardCRModelPropertyIface MidgardCRModelPropertyIface;

#define MIDGARD_CR_TYPE_SCHEMA_MODEL (midgard_cr_schema_model_get_type ())
#define MIDGARD_CR_SCHEMA_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SCHEMA_MODEL, MidgardCRSchemaModel))
#define MIDGARD_CR_SCHEMA_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SCHEMA_MODEL, MidgardCRSchemaModelClass))
#define MIDGARD_CR_IS_SCHEMA_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SCHEMA_MODEL))
#define MIDGARD_CR_IS_SCHEMA_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SCHEMA_MODEL))
#define MIDGARD_CR_SCHEMA_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SCHEMA_MODEL, MidgardCRSchemaModelClass))

typedef struct _MidgardCRSchemaModel MidgardCRSchemaModel;
typedef struct _MidgardCRSchemaModelClass MidgardCRSchemaModelClass;
typedef struct _MidgardCRSchemaModelPrivate MidgardCRSchemaModelPrivate;

#define MIDGARD_CR_TYPE_SCHEMA_MODEL_PROPERTY (midgard_cr_schema_model_property_get_type ())
#define MIDGARD_CR_SCHEMA_MODEL_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SCHEMA_MODEL_PROPERTY, MidgardCRSchemaModelProperty))
#define MIDGARD_CR_SCHEMA_MODEL_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SCHEMA_MODEL_PROPERTY, MidgardCRSchemaModelPropertyClass))
#define MIDGARD_CR_IS_SCHEMA_MODEL_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SCHEMA_MODEL_PROPERTY))
#define MIDGARD_CR_IS_SCHEMA_MODEL_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SCHEMA_MODEL_PROPERTY))
#define MIDGARD_CR_SCHEMA_MODEL_PROPERTY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SCHEMA_MODEL_PROPERTY, MidgardCRSchemaModelPropertyClass))

typedef struct _MidgardCRSchemaModelProperty MidgardCRSchemaModelProperty;
typedef struct _MidgardCRSchemaModelPropertyClass MidgardCRSchemaModelPropertyClass;
typedef struct _MidgardCRSchemaModelPropertyPrivate MidgardCRSchemaModelPropertyPrivate;

#define MIDGARD_CR_TYPE_SCHEMA_BUILDER (midgard_cr_schema_builder_get_type ())
#define MIDGARD_CR_SCHEMA_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SCHEMA_BUILDER, MidgardCRSchemaBuilder))
#define MIDGARD_CR_SCHEMA_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SCHEMA_BUILDER, MidgardCRSchemaBuilderClass))
#define MIDGARD_CR_IS_SCHEMA_BUILDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SCHEMA_BUILDER))
#define MIDGARD_CR_IS_SCHEMA_BUILDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SCHEMA_BUILDER))
#define MIDGARD_CR_SCHEMA_BUILDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SCHEMA_BUILDER, MidgardCRSchemaBuilderClass))

typedef struct _MidgardCRSchemaBuilder MidgardCRSchemaBuilder;
typedef struct _MidgardCRSchemaBuilderClass MidgardCRSchemaBuilderClass;
typedef struct _MidgardCRSchemaBuilderPrivate MidgardCRSchemaBuilderPrivate;

#define MIDGARD_CR_TYPE_STORAGE_MANAGER (midgard_cr_storage_manager_get_type ())
#define MIDGARD_CR_STORAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_MANAGER, MidgardCRStorageManager))
#define MIDGARD_CR_IS_STORAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_MANAGER))
#define MIDGARD_CR_STORAGE_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_MANAGER, MidgardCRStorageManagerIface))

typedef struct _MidgardCRStorageManager MidgardCRStorageManager;
typedef struct _MidgardCRStorageManagerIface MidgardCRStorageManagerIface;

#define MIDGARD_CR_TYPE_STORAGE_CONTENT_MANAGER (midgard_cr_storage_content_manager_get_type ())
#define MIDGARD_CR_STORAGE_CONTENT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_CONTENT_MANAGER, MidgardCRStorageContentManager))
#define MIDGARD_CR_IS_STORAGE_CONTENT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_CONTENT_MANAGER))
#define MIDGARD_CR_STORAGE_CONTENT_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_CONTENT_MANAGER, MidgardCRStorageContentManagerIface))

typedef struct _MidgardCRStorageContentManager MidgardCRStorageContentManager;
typedef struct _MidgardCRStorageContentManagerIface MidgardCRStorageContentManagerIface;

#define MIDGARD_CR_TYPE_QUERY_MANAGER (midgard_cr_query_manager_get_type ())
#define MIDGARD_CR_QUERY_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_QUERY_MANAGER, MidgardCRQueryManager))
#define MIDGARD_CR_IS_QUERY_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_QUERY_MANAGER))
#define MIDGARD_CR_QUERY_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_QUERY_MANAGER, MidgardCRQueryManagerIface))

typedef struct _MidgardCRQueryManager MidgardCRQueryManager;
typedef struct _MidgardCRQueryManagerIface MidgardCRQueryManagerIface;

#define MIDGARD_CR_TYPE_STORAGE_EXECUTOR (midgard_cr_storage_executor_get_type ())
#define MIDGARD_CR_STORAGE_EXECUTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_EXECUTOR, MidgardCRStorageExecutor))
#define MIDGARD_CR_IS_STORAGE_EXECUTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_EXECUTOR))
#define MIDGARD_CR_STORAGE_EXECUTOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_EXECUTOR, MidgardCRStorageExecutorIface))

typedef struct _MidgardCRStorageExecutor MidgardCRStorageExecutor;
typedef struct _MidgardCRStorageExecutorIface MidgardCRStorageExecutorIface;

#define MIDGARD_CR_TYPE_STORAGE_MODEL_MANAGER (midgard_cr_storage_model_manager_get_type ())
#define MIDGARD_CR_STORAGE_MODEL_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL_MANAGER, MidgardCRStorageModelManager))
#define MIDGARD_CR_IS_STORAGE_MODEL_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL_MANAGER))
#define MIDGARD_CR_STORAGE_MODEL_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL_MANAGER, MidgardCRStorageModelManagerIface))

typedef struct _MidgardCRStorageModelManager MidgardCRStorageModelManager;
typedef struct _MidgardCRStorageModelManagerIface MidgardCRStorageModelManagerIface;

#define MIDGARD_CR_TYPE_STORAGE_MODEL (midgard_cr_storage_model_get_type ())
#define MIDGARD_CR_STORAGE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL, MidgardCRStorageModel))
#define MIDGARD_CR_IS_STORAGE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL))
#define MIDGARD_CR_STORAGE_MODEL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL, MidgardCRStorageModelIface))

typedef struct _MidgardCRStorageModel MidgardCRStorageModel;
typedef struct _MidgardCRStorageModelIface MidgardCRStorageModelIface;

#define MIDGARD_CR_TYPE_TRANSACTION (midgard_cr_transaction_get_type ())
#define MIDGARD_CR_TRANSACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_TRANSACTION, MidgardCRTransaction))
#define MIDGARD_CR_IS_TRANSACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_TRANSACTION))
#define MIDGARD_CR_TRANSACTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_TRANSACTION, MidgardCRTransactionIface))

typedef struct _MidgardCRTransaction MidgardCRTransaction;
typedef struct _MidgardCRTransactionIface MidgardCRTransactionIface;

#define MIDGARD_CR_TYPE_STORAGE_WORKSPACE_MANAGER (midgard_cr_storage_workspace_manager_get_type ())
#define MIDGARD_CR_STORAGE_WORKSPACE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_WORKSPACE_MANAGER, MidgardCRStorageWorkspaceManager))
#define MIDGARD_CR_IS_STORAGE_WORKSPACE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_WORKSPACE_MANAGER))
#define MIDGARD_CR_STORAGE_WORKSPACE_MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_WORKSPACE_MANAGER, MidgardCRStorageWorkspaceManagerIface))

typedef struct _MidgardCRStorageWorkspaceManager MidgardCRStorageWorkspaceManager;
typedef struct _MidgardCRStorageWorkspaceManagerIface MidgardCRStorageWorkspaceManagerIface;

#define MIDGARD_CR_TYPE_WORKSPACE_STORAGE (midgard_cr_workspace_storage_get_type ())
#define MIDGARD_CR_WORKSPACE_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_WORKSPACE_STORAGE, MidgardCRWorkspaceStorage))
#define MIDGARD_CR_IS_WORKSPACE_STORAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_WORKSPACE_STORAGE))
#define MIDGARD_CR_WORKSPACE_STORAGE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_WORKSPACE_STORAGE, MidgardCRWorkspaceStorageIface))

typedef struct _MidgardCRWorkspaceStorage MidgardCRWorkspaceStorage;
typedef struct _MidgardCRWorkspaceStorageIface MidgardCRWorkspaceStorageIface;

#define MIDGARD_CR_TYPE_TIMESTAMP (midgard_cr_timestamp_get_type ())
#define MIDGARD_CR_TIMESTAMP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_TIMESTAMP, MidgardCRTimestamp))
#define MIDGARD_CR_TIMESTAMP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_TIMESTAMP, MidgardCRTimestampClass))
#define MIDGARD_CR_IS_TIMESTAMP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_TIMESTAMP))
#define MIDGARD_CR_IS_TIMESTAMP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_TIMESTAMP))
#define MIDGARD_CR_TIMESTAMP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_TIMESTAMP, MidgardCRTimestampClass))

typedef struct _MidgardCRTimestamp MidgardCRTimestamp;
typedef struct _MidgardCRTimestampClass MidgardCRTimestampClass;
typedef struct _MidgardCRTimestampPrivate MidgardCRTimestampPrivate;

#define MIDGARD_CR_TYPE_METADATA (midgard_cr_metadata_get_type ())
#define MIDGARD_CR_METADATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_METADATA, MidgardCRMetadata))
#define MIDGARD_CR_METADATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_METADATA, MidgardCRMetadataClass))
#define MIDGARD_CR_IS_METADATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_METADATA))
#define MIDGARD_CR_IS_METADATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_METADATA))
#define MIDGARD_CR_METADATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_METADATA, MidgardCRMetadataClass))

typedef struct _MidgardCRMetadata MidgardCRMetadata;
typedef struct _MidgardCRMetadataClass MidgardCRMetadataClass;
typedef struct _MidgardCRMetadataPrivate MidgardCRMetadataPrivate;

#define MIDGARD_CR_TYPE_SCHEMA_OBJECT (midgard_cr_schema_object_get_type ())
#define MIDGARD_CR_SCHEMA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SCHEMA_OBJECT, MidgardCRSchemaObject))
#define MIDGARD_CR_SCHEMA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SCHEMA_OBJECT, MidgardCRSchemaObjectClass))
#define MIDGARD_CR_IS_SCHEMA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SCHEMA_OBJECT))
#define MIDGARD_CR_IS_SCHEMA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SCHEMA_OBJECT))
#define MIDGARD_CR_SCHEMA_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SCHEMA_OBJECT, MidgardCRSchemaObjectClass))

typedef struct _MidgardCRSchemaObject MidgardCRSchemaObject;
typedef struct _MidgardCRSchemaObjectClass MidgardCRSchemaObjectClass;
typedef struct _MidgardCRSchemaObjectPrivate MidgardCRSchemaObjectPrivate;

#define MIDGARD_CR_TYPE_DB_OBJECT (midgard_cr_db_object_get_type ())
#define MIDGARD_CR_DB_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_DB_OBJECT, MidgardCRDBObject))
#define MIDGARD_CR_DB_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_DB_OBJECT, MidgardCRDBObjectClass))
#define MIDGARD_CR_IS_DB_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_DB_OBJECT))
#define MIDGARD_CR_IS_DB_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_DB_OBJECT))
#define MIDGARD_CR_DB_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_DB_OBJECT, MidgardCRDBObjectClass))

typedef struct _MidgardCRDBObject MidgardCRDBObject;
typedef struct _MidgardCRDBObjectClass MidgardCRDBObjectClass;
typedef struct _MidgardCRDBObjectPrivate MidgardCRDBObjectPrivate;

#define MIDGARD_CR_TYPE_SQL_STORAGE_MANAGER (midgard_cr_sql_storage_manager_get_type ())
#define MIDGARD_CR_SQL_STORAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SQL_STORAGE_MANAGER, MidgardCRSQLStorageManager))
#define MIDGARD_CR_SQL_STORAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SQL_STORAGE_MANAGER, MidgardCRSQLStorageManagerClass))
#define MIDGARD_CR_IS_SQL_STORAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SQL_STORAGE_MANAGER))
#define MIDGARD_CR_IS_SQL_STORAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SQL_STORAGE_MANAGER))
#define MIDGARD_CR_SQL_STORAGE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SQL_STORAGE_MANAGER, MidgardCRSQLStorageManagerClass))

typedef struct _MidgardCRSQLStorageManager MidgardCRSQLStorageManager;
typedef struct _MidgardCRSQLStorageManagerClass MidgardCRSQLStorageManagerClass;
typedef struct _MidgardCRSQLStorageManagerPrivate MidgardCRSQLStorageManagerPrivate;

#define MIDGARD_CR_TYPE_STORAGE_MANAGER_POOL (midgard_cr_storage_manager_pool_get_type ())
#define MIDGARD_CR_STORAGE_MANAGER_POOL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_MANAGER_POOL, MidgardCRStorageManagerPool))
#define MIDGARD_CR_IS_STORAGE_MANAGER_POOL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_MANAGER_POOL))
#define MIDGARD_CR_STORAGE_MANAGER_POOL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_MANAGER_POOL, MidgardCRStorageManagerPoolIface))

typedef struct _MidgardCRStorageManagerPool MidgardCRStorageManagerPool;
typedef struct _MidgardCRStorageManagerPoolIface MidgardCRStorageManagerPoolIface;

#define MIDGARD_CR_TYPE_STORAGE_MODEL_PROPERTY (midgard_cr_storage_model_property_get_type ())
#define MIDGARD_CR_STORAGE_MODEL_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL_PROPERTY, MidgardCRStorageModelProperty))
#define MIDGARD_CR_IS_STORAGE_MODEL_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL_PROPERTY))
#define MIDGARD_CR_STORAGE_MODEL_PROPERTY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDGARD_CR_TYPE_STORAGE_MODEL_PROPERTY, MidgardCRStorageModelPropertyIface))

typedef struct _MidgardCRStorageModelProperty MidgardCRStorageModelProperty;
typedef struct _MidgardCRStorageModelPropertyIface MidgardCRStorageModelPropertyIface;

#define MIDGARD_CR_TYPE_WORKSPACE_CONTEXT (midgard_cr_workspace_context_get_type ())
#define MIDGARD_CR_WORKSPACE_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_WORKSPACE_CONTEXT, MidgardCRWorkspaceContext))
#define MIDGARD_CR_WORKSPACE_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_WORKSPACE_CONTEXT, MidgardCRWorkspaceContextClass))
#define MIDGARD_CR_IS_WORKSPACE_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_WORKSPACE_CONTEXT))
#define MIDGARD_CR_IS_WORKSPACE_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_WORKSPACE_CONTEXT))
#define MIDGARD_CR_WORKSPACE_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_WORKSPACE_CONTEXT, MidgardCRWorkspaceContextClass))

typedef struct _MidgardCRWorkspaceContext MidgardCRWorkspaceContext;
typedef struct _MidgardCRWorkspaceContextClass MidgardCRWorkspaceContextClass;
typedef struct _MidgardCRWorkspaceContextPrivate MidgardCRWorkspaceContextPrivate;

#define MIDGARD_CR_TYPE_WORKSPACE (midgard_cr_workspace_get_type ())
#define MIDGARD_CR_WORKSPACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_WORKSPACE, MidgardCRWorkspace))
#define MIDGARD_CR_WORKSPACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_WORKSPACE, MidgardCRWorkspaceClass))
#define MIDGARD_CR_IS_WORKSPACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_WORKSPACE))
#define MIDGARD_CR_IS_WORKSPACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_WORKSPACE))
#define MIDGARD_CR_WORKSPACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_WORKSPACE, MidgardCRWorkspaceClass))

typedef struct _MidgardCRWorkspace MidgardCRWorkspace;
typedef struct _MidgardCRWorkspaceClass MidgardCRWorkspaceClass;
typedef struct _MidgardCRWorkspacePrivate MidgardCRWorkspacePrivate;

#define MIDGARD_CR_TYPE_SQL_WORKSPACE_MANAGER (midgard_cr_sql_workspace_manager_get_type ())
#define MIDGARD_CR_SQL_WORKSPACE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SQL_WORKSPACE_MANAGER, MidgardCRSQLWorkspaceManager))
#define MIDGARD_CR_SQL_WORKSPACE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SQL_WORKSPACE_MANAGER, MidgardCRSQLWorkspaceManagerClass))
#define MIDGARD_CR_IS_SQL_WORKSPACE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SQL_WORKSPACE_MANAGER))
#define MIDGARD_CR_IS_SQL_WORKSPACE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SQL_WORKSPACE_MANAGER))
#define MIDGARD_CR_SQL_WORKSPACE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SQL_WORKSPACE_MANAGER, MidgardCRSQLWorkspaceManagerClass))

typedef struct _MidgardCRSQLWorkspaceManager MidgardCRSQLWorkspaceManager;
typedef struct _MidgardCRSQLWorkspaceManagerClass MidgardCRSQLWorkspaceManagerClass;
typedef struct _MidgardCRSQLWorkspaceManagerPrivate MidgardCRSQLWorkspaceManagerPrivate;

#define MIDGARD_CR_TYPE_SQL_STORAGE_MODEL_MANAGER (midgard_cr_sql_storage_model_manager_get_type ())
#define MIDGARD_CR_SQL_STORAGE_MODEL_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_CR_TYPE_SQL_STORAGE_MODEL_MANAGER, MidgardCRSQLStorageModelManager))
#define MIDGARD_CR_SQL_STORAGE_MODEL_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_CR_TYPE_SQL_STORAGE_MODEL_MANAGER, MidgardCRSQLStorageModelManagerClass))
#define MIDGARD_CR_IS_SQL_STORAGE_MODEL_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_CR_TYPE_SQL_STORAGE_MODEL_MANAGER))
#define MIDGARD_CR_IS_SQL_STORAGE_MODEL_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_CR_TYPE_SQL_STORAGE_MODEL_MANAGER))
#define MIDGARD_CR_SQL_STORAGE_MODEL_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_CR_TYPE_SQL_STORAGE_MODEL_MANAGER, MidgardCRSQLStorageModelManagerClass))

typedef struct _MidgardCRSQLStorageModelManager MidgardCRSQLStorageModelManager;
typedef struct _MidgardCRSQLStorageModelManagerClass MidgardCRSQLStorageModelManagerClass;
typedef struct _MidgardCRSQLStorageModelManagerPrivate MidgardCRSQLStorageModelManagerPrivate;

struct _MidgardCRConfig {
	GObject parent_instance;
	MidgardCRConfigPrivate * priv;
	guint dbtype_id;
	GKeyFile* keyfile;
};

struct _MidgardCRConfigClass {
	GObjectClass parent_class;
};

typedef enum  {
	MIDGARD_CR_EXECUTABLE_ERROR_DEPENDENCE_INVALID,
	MIDGARD_CR_EXECUTABLE_ERROR_COMMAND_INVALID,
	MIDGARD_CR_EXECUTABLE_ERROR_COMMAND_INVALID_DATA,
	MIDGARD_CR_EXECUTABLE_ERROR_INTERNAL
} MidgardCRExecutableError;
#define MIDGARD_CR_EXECUTABLE_ERROR midgard_cr_executable_error_quark ()
struct _MidgardCRExecutableIface {
	GTypeInterface parent_iface;
	void (*execute) (MidgardCRExecutable* self, GError** error);
};

typedef enum  {
	MIDGARD_CR_NAMESPACE_MANAGER_ERROR_URI_INVALID,
	MIDGARD_CR_NAMESPACE_MANAGER_ERROR_URI_EXISTS,
	MIDGARD_CR_NAMESPACE_MANAGER_ERROR_ALIAS_INVALID,
	MIDGARD_CR_NAMESPACE_MANAGER_ERROR_ALIAS_EXISTS
} MidgardCRNamespaceManagerError;
#define MIDGARD_CR_NAMESPACE_MANAGER_ERROR midgard_cr_namespace_manager_error_quark ()
struct _MidgardCRNamespaceManagerIface {
	GTypeInterface parent_iface;
	gboolean (*create_uri) (MidgardCRNamespaceManager* self, const char* uri, const char* name, GError** error);
	char** (*list_names) (MidgardCRNamespaceManager* self, int* result_length1);
	char* (*get_uri_by_name) (MidgardCRNamespaceManager* self, const char* name);
	char* (*get_name_by_uri) (MidgardCRNamespaceManager* self, const char* uri);
	gboolean (*name_exists) (MidgardCRNamespaceManager* self);
	gboolean (*uri_exists) (MidgardCRNamespaceManager* self);
};

struct _MidgardCRProfilerIface {
	GTypeInterface parent_iface;
	void (*enable) (MidgardCRProfiler* self, gboolean toggle);
	void (*start) (MidgardCRProfiler* self);
	void (*end) (MidgardCRProfiler* self);
	gint (*get_time) (MidgardCRProfiler* self);
	char* (*get_execution_command) (MidgardCRProfiler* self);
};

struct _MidgardCRQueryConstraintSimpleIface {
	GTypeInterface parent_iface;
	MidgardCRQueryConstraintSimple** (*list_constraints) (MidgardCRQueryConstraintSimple* self, int* result_length1);
};

struct _MidgardCRQueryStorageIface {
	GTypeInterface parent_iface;
	const char* (*get_classname) (MidgardCRQueryStorage* self);
	void (*set_classname) (MidgardCRQueryStorage* self, const char* value);
};

struct _MidgardCRQueryValueHolderIface {
	GTypeInterface parent_iface;
	void (*get_value) (MidgardCRQueryValueHolder* self, GValue* result);
	void (*set_value) (MidgardCRQueryValueHolder* self, GValue* value);
};

struct _MidgardCRQueryConstraintIface {
	GTypeInterface parent_iface;
	MidgardCRQueryValueHolder* (*get_holder) (MidgardCRQueryConstraint* self);
	void (*set_holder) (MidgardCRQueryConstraint* self, MidgardCRQueryValueHolder* value);
	MidgardCRQueryProperty* (*get_property) (MidgardCRQueryConstraint* self);
	void (*set_property) (MidgardCRQueryConstraint* self, MidgardCRQueryProperty* value);
	MidgardCRQueryStorage* (*get_storage) (MidgardCRQueryConstraint* self);
	void (*set_storage) (MidgardCRQueryConstraint* self, MidgardCRQueryStorage* value);
	const char* (*get_operator) (MidgardCRQueryConstraint* self);
	void (*set_operator) (MidgardCRQueryConstraint* self, const char* value);
};

struct _MidgardCRQueryConstraintGroupIface {
	GTypeInterface parent_iface;
	char* (*get_group_type) (MidgardCRQueryConstraintGroup* self);
	void (*set_group_type) (MidgardCRQueryConstraintGroup* self, const char* name);
	void (*add_constraint) (MidgardCRQueryConstraintGroup* self, MidgardCRQueryConstraintSimple* constraint);
	const char* (*get_grouptype) (MidgardCRQueryConstraintGroup* self);
	void (*set_grouptype) (MidgardCRQueryConstraintGroup* self, const char* value);
};

struct _MidgardCRQueryValue {
	GObject parent_instance;
	MidgardCRQueryValuePrivate * priv;
};

struct _MidgardCRQueryValueClass {
	GObjectClass parent_class;
};

struct _MidgardCRQueryProperty {
	GObject parent_instance;
	MidgardCRQueryPropertyPrivate * priv;
};

struct _MidgardCRQueryPropertyClass {
	GObjectClass parent_class;
};

typedef enum  {
	MIDGARD_CR_VALIDATION_ERROR_NAME_INVALID,
	MIDGARD_CR_VALIDATION_ERROR_NAME_DUPLICATED,
	MIDGARD_CR_VALIDATION_ERROR_TYPE_INVALID,
	MIDGARD_CR_VALIDATION_ERROR_VALUE_INVALID,
	MIDGARD_CR_VALIDATION_ERROR_REFERENCE_INVALID,
	MIDGARD_CR_VALIDATION_ERROR_PARENT_INVALID,
	MIDGARD_CR_VALIDATION_ERROR_LOCATION_INVALID,
	MIDGARD_CR_VALIDATION_ERROR_INTERNAL
} MidgardCRValidationError;
#define MIDGARD_CR_VALIDATION_ERROR midgard_cr_validation_error_quark ()
struct _MidgardCRQueryExecutorIface {
	GTypeInterface parent_iface;
	void (*set_constraint) (MidgardCRQueryExecutor* self, MidgardCRQueryConstraintSimple* constraint);
	void (*set_limit) (MidgardCRQueryExecutor* self, guint limit);
	void (*set_offset) (MidgardCRQueryExecutor* self, guint offset);
	void (*add_order) (MidgardCRQueryExecutor* self, MidgardCRQueryProperty* property, const char* type);
	guint (*get_results_count) (MidgardCRQueryExecutor* self);
	void (*validate) (MidgardCRQueryExecutor* self, GError** error);
};

struct _MidgardCRStorableIface {
	GTypeInterface parent_iface;
};

struct _MidgardCRQuerySelectIface {
	GTypeInterface parent_iface;
	void (*add_join) (MidgardCRQuerySelect* self, const char* type, MidgardCRQueryProperty* left_property, MidgardCRQueryProperty* right_property);
	MidgardCRStorable** (*list_objects) (MidgardCRQuerySelect* self, int* result_length1);
	void (*toggle_read_only) (MidgardCRQuerySelect* self, gboolean toggle);
};

struct _MidgardCRQueryDataIface {
	GTypeInterface parent_iface;
	void (*add_join) (MidgardCRQueryData* self, const char* type, MidgardCRQueryProperty* left_property, MidgardCRQueryProperty* right_property);
	void (*collect_property) (MidgardCRQueryData* self, MidgardCRQueryProperty* property, MidgardCRQueryStorage* storage);
	void (*list_data) (MidgardCRQueryData* self);
};

struct _MidgardCRModelIface {
	GTypeInterface parent_iface;
	MidgardCRModel* (*add_model) (MidgardCRModel* self, MidgardCRModel* model);
	MidgardCRModel* (*get_model_by_name) (MidgardCRModel* self, const char* name);
	MidgardCRModel** (*list_models) (MidgardCRModel* self, int* result_length1);
	MidgardCRModelReflector* (*get_reflector) (MidgardCRModel* self);
	void (*is_valid) (MidgardCRModel* self, GError** error);
	MidgardCRModel* (*get_parent) (MidgardCRModel* self);
	void (*set_parent) (MidgardCRModel* self, MidgardCRModel* value);
	const char* (*get_namespace) (MidgardCRModel* self);
	void (*set_namespace) (MidgardCRModel* self, const char* value);
	const char* (*get_name) (MidgardCRModel* self);
	void (*set_name) (MidgardCRModel* self, const char* value);
};

struct _MidgardCRModelReflectorIface {
	GTypeInterface parent_iface;
	MidgardCRModel* (*get_model) (MidgardCRModelReflector* self);
	void (*set_model) (MidgardCRModelReflector* self, MidgardCRModel* value);
};

struct _MidgardCRModelPropertyReflectorIface {
	GTypeInterface parent_iface;
	char* (*get_typename) (MidgardCRModelPropertyReflector* self);
	GType (*get_gtype) (MidgardCRModelPropertyReflector* self);
	void (*get_default_value) (MidgardCRModelPropertyReflector* self, GValue* result);
	gboolean (*is_private) (MidgardCRModelPropertyReflector* self);
	char* (*get_description) (MidgardCRModelPropertyReflector* self);
};

struct _MidgardCRModelPropertyIface {
	GTypeInterface parent_iface;
	GType (*get_valuegtype) (MidgardCRModelProperty* self);
	const char* (*get_valuetypename) (MidgardCRModelProperty* self);
	void (*set_valuetypename) (MidgardCRModelProperty* self, const char* value);
	const char* (*get_valuedefault) (MidgardCRModelProperty* self);
	void (*set_valuedefault) (MidgardCRModelProperty* self, const char* value);
	const char* (*get_description) (MidgardCRModelProperty* self);
	void (*set_description) (MidgardCRModelProperty* self, const char* value);
	gboolean (*get_private) (MidgardCRModelProperty* self);
	void (*set_private) (MidgardCRModelProperty* self, gboolean value);
};

struct _MidgardCRSchemaModel {
	GObject parent_instance;
	MidgardCRSchemaModelPrivate * priv;
};

struct _MidgardCRSchemaModelClass {
	GObjectClass parent_class;
};

struct _MidgardCRSchemaModelProperty {
	GObject parent_instance;
	MidgardCRSchemaModelPropertyPrivate * priv;
};

struct _MidgardCRSchemaModelPropertyClass {
	GObjectClass parent_class;
};

typedef enum  {
	MIDGARD_CR_SCHEMA_BUILDER_ERROR_NAME_EXISTS
} MidgardCRSchemaBuilderError;
#define MIDGARD_CR_SCHEMA_BUILDER_ERROR midgard_cr_schema_builder_error_quark ()
struct _MidgardCRSchemaBuilder {
	GObject parent_instance;
	MidgardCRSchemaBuilderPrivate * priv;
	MidgardCRSchemaModel** _models;
	gint _models_length1;
	gint __models_size_;
	MidgardCRSchemaModel** _delayed_models;
	gint _delayed_models_length1;
	gint __delayed_models_size_;
};

struct _MidgardCRSchemaBuilderClass {
	GObjectClass parent_class;
};

typedef enum  {
	MIDGARD_CR_STORAGE_MANAGER_ERROR_ACCESS_DENIED,
	MIDGARD_CR_STORAGE_MANAGER_ERROR_NAME_INVALID,
	MIDGARD_CR_STORAGE_MANAGER_ERROR_NOT_OPENED,
	MIDGARD_CR_STORAGE_MANAGER_ERROR_INTERNAL
} MidgardCRStorageManagerError;
#define MIDGARD_CR_STORAGE_MANAGER_ERROR midgard_cr_storage_manager_error_quark ()
typedef enum  {
	MIDGARD_CR_STORAGE_CONTENT_MANAGER_ERROR_OBJECT_INVALID,
	MIDGARD_CR_STORAGE_CONTENT_MANAGER_ERROR_OBJECT_DUPLICATE,
	MIDGARD_CR_STORAGE_CONTENT_MANAGER_ERROR_INTERNAL
} MidgardCRStorageContentManagerError;
#define MIDGARD_CR_STORAGE_CONTENT_MANAGER_ERROR midgard_cr_storage_content_manager_error_quark ()
struct _MidgardCRQueryManagerIface {
	GTypeInterface parent_iface;
};

struct _MidgardCRStorageContentManagerIface {
	GTypeInterface parent_iface;
	MidgardCRStorageManager* (*get_storage_manager) (MidgardCRStorageContentManager* self);
	gboolean (*exists) (MidgardCRStorageContentManager* self, MidgardCRStorable* object);
	gboolean (*create) (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
	gboolean (*update) (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
	gboolean (*save) (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
	gboolean (*remove) (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
	gboolean (*purge) (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
	MidgardCRQueryManager* (*get_query_manager) (MidgardCRStorageContentManager* self);
};

struct _MidgardCRStorageExecutorIface {
	GTypeInterface parent_iface;
	gboolean (*exists) (MidgardCRStorageExecutor* self);
	void (*prepare_create) (MidgardCRStorageExecutor* self, GError** error);
	void (*prepare_update) (MidgardCRStorageExecutor* self, GError** error);
	void (*prepare_save) (MidgardCRStorageExecutor* self, GError** error);
	void (*prepare_remove) (MidgardCRStorageExecutor* self, GError** error);
	void (*prepare_purge) (MidgardCRStorageExecutor* self, GError** error);
};

typedef enum  {
	MIDGARD_CR_STORAGE_MODEL_ERROR_STORAGE_INVALID,
	MIDGARD_CR_STORAGE_MODEL_ERROR_STORAGE_EXISTS,
	MIDGARD_CR_STORAGE_MODEL_ERROR_INTERNAL
} MidgardCRStorageModelError;
#define MIDGARD_CR_STORAGE_MODEL_ERROR midgard_cr_storage_model_error_quark ()
struct _MidgardCRStorageModelIface {
	GTypeInterface parent_iface;
	gboolean (*location_set) (MidgardCRStorageModel* self, const char* location, GError** error);
	char* (*location_get) (MidgardCRStorageModel* self);
};

struct _MidgardCRStorageModelManagerIface {
	GTypeInterface parent_iface;
	MidgardCRStorageModel* (*create_storage_model) (MidgardCRStorageModelManager* self, MidgardCRSchemaModel* schema_model, const char* location);
	MidgardCRStorageModel** (*list_storage_models) (MidgardCRStorageModelManager* self, int* result_length1);
	MidgardCRSchemaModel** (*list_schema_models) (MidgardCRStorageModelManager* self, int* result_length1);
	MidgardCRNamespaceManager* (*get_namespace_manager) (MidgardCRStorageModelManager* self);
	MidgardCRStorageManager* (*get_storage_manager) (MidgardCRStorageModelManager* self);
};

struct _MidgardCRTransactionIface {
	GTypeInterface parent_iface;
	gboolean (*begin) (MidgardCRTransaction* self);
	gboolean (*rollback) (MidgardCRTransaction* self);
	gboolean (*get_status) (MidgardCRTransaction* self);
	const char* (*get_name) (MidgardCRTransaction* self);
	void (*set_name) (MidgardCRTransaction* self, const char* value);
};

struct _MidgardCRWorkspaceStorageIface {
	GTypeInterface parent_iface;
	const char* (*get_path) (MidgardCRWorkspaceStorage* self);
	void (*set_path) (MidgardCRWorkspaceStorage* self, const char* value);
};

struct _MidgardCRStorageWorkspaceManagerIface {
	GTypeInterface parent_iface;
	MidgardCRWorkspaceStorage* (*get_workspace) (MidgardCRStorageWorkspaceManager* self);
	void (*set_workspace) (MidgardCRStorageWorkspaceManager* self, MidgardCRWorkspaceStorage* value);
};

struct _MidgardCRStorageManagerIface {
	GTypeInterface parent_iface;
	gboolean (*open) (MidgardCRStorageManager* self, GError** error);
	gboolean (*close) (MidgardCRStorageManager* self, GError** error);
	gboolean (*initialize_storage) (MidgardCRStorageManager* self, GError** error);
	MidgardCRStorageManager* (*fork) (MidgardCRStorageManager* self);
	MidgardCRStorageManager* (*clone) (MidgardCRStorageManager* self);
	MidgardCRStorageContentManager* (*get_content_manager) (MidgardCRStorageManager* self);
	MidgardCRStorageModelManager* (*get_model_manager) (MidgardCRStorageManager* self);
	MidgardCRProfiler* (*get_profiler) (MidgardCRStorageManager* self);
	MidgardCRTransaction* (*get_transaction) (MidgardCRStorageManager* self);
	MidgardCRStorageWorkspaceManager* (*get_workspace_manager) (MidgardCRStorageManager* self);
};

struct _MidgardCRTimestamp {
	GObject parent_instance;
	MidgardCRTimestampPrivate * priv;
};

struct _MidgardCRTimestampClass {
	GObjectClass parent_class;
};

struct _MidgardCRMetadata {
	GObject parent_instance;
	MidgardCRMetadataPrivate * priv;
};

struct _MidgardCRMetadataClass {
	GObjectClass parent_class;
	const char* (*get_parent) (MidgardCRMetadata* self);
	void (*set_parent) (MidgardCRMetadata* self, const char* value);
	guint (*get_action) (MidgardCRMetadata* self);
	MidgardCRTimestamp* (*get_created) (MidgardCRMetadata* self);
	MidgardCRTimestamp* (*get_revised) (MidgardCRMetadata* self);
};

struct _MidgardCRSchemaObject {
	GObject parent_instance;
	MidgardCRSchemaObjectPrivate * priv;
};

struct _MidgardCRSchemaObjectClass {
	GObjectClass parent_class;
	void (*set_property_value) (MidgardCRSchemaObject* self, const char* name, GValue* value);
	void (*get_property_value) (MidgardCRSchemaObject* self, const char* name, GValue* result);
	char** (*list_all_properties) (MidgardCRSchemaObject* self, int* result_length1);
};

struct _MidgardCRDBObject {
	GObject parent_instance;
	MidgardCRDBObjectPrivate * priv;
};

struct _MidgardCRDBObjectClass {
	GObjectClass parent_class;
};

struct _MidgardCRSQLStorageManager {
	GObject parent_instance;
	MidgardCRSQLStorageManagerPrivate * priv;
	GObject* _cnc;
	GObject* _parser;
	MidgardCRSchemaModel** _schema_models;
	gint _schema_models_length1;
	gint __schema_models_size_;
	MidgardCRStorageModel** _storage_models;
	gint _storage_models_length1;
	gint __storage_models_size_;
};

struct _MidgardCRSQLStorageManagerClass {
	GObjectClass parent_class;
};

struct _MidgardCRStorageManagerPoolIface {
	GTypeInterface parent_iface;
	void (*register_manager_type) (MidgardCRStorageManagerPool* self, const char* classname);
	MidgardCRStorageManager* (*create_manager) (MidgardCRStorageManagerPool* self, const char* classname, const char* name);
	char** (*list_managers) (MidgardCRStorageManagerPool* self, int* result_length1);
	MidgardCRStorageManager* (*get_manager_by_name) (MidgardCRStorageManagerPool* self, const char* name);
};

struct _MidgardCRStorageModelPropertyIface {
	GTypeInterface parent_iface;
	void (*set_primary) (MidgardCRStorageModelProperty* self, gboolean toggle);
	gboolean (*is_primary) (MidgardCRStorageModelProperty* self);
	void (*set_index) (MidgardCRStorageModelProperty* self, gboolean toggle);
	gboolean (*has_index) (MidgardCRStorageModelProperty* self);
	gboolean (*location_set) (MidgardCRStorageModelProperty* self, const char* location);
	char* (*location_get) (MidgardCRStorageModelProperty* self);
};

typedef enum  {
	MIDGARD_CR_WORKSPACE_STORAGE_ERROR_WORKSPACE_STORAGE_ERROR_NAME_EXISTS,
	MIDGARD_CR_WORKSPACE_STORAGE_ERROR_WORKSPACE_STORAGE_ERROR_INVALID_PATH,
	MIDGARD_CR_WORKSPACE_STORAGE_ERROR_WORKSPACE_STORAGE_ERROR_OBJECT_NOT_EXISTS,
	MIDGARD_CR_WORKSPACE_STORAGE_ERROR_WORKSPACE_STORAGE_ERROR_CONTEXT_VIOLATION
} MidgardCRWorkspaceStorageError;
#define MIDGARD_CR_WORKSPACE_STORAGE_ERROR midgard_cr_workspace_storage_error_quark ()
struct _MidgardCRWorkspaceContext {
	GObject parent_instance;
	MidgardCRWorkspaceContextPrivate * priv;
};

struct _MidgardCRWorkspaceContextClass {
	GObjectClass parent_class;
};

struct _MidgardCRWorkspace {
	GObject parent_instance;
	MidgardCRWorkspacePrivate * priv;
};

struct _MidgardCRWorkspaceClass {
	GObjectClass parent_class;
};

struct _MidgardCRSQLWorkspaceManager {
	MidgardCRSQLStorageManager parent_instance;
	MidgardCRSQLWorkspaceManagerPrivate * priv;
};

struct _MidgardCRSQLWorkspaceManagerClass {
	MidgardCRSQLStorageManagerClass parent_class;
};

struct _MidgardCRSQLStorageModelManager {
	GObject parent_instance;
	MidgardCRSQLStorageModelManagerPrivate * priv;
	MidgardCRSQLStorageManager* _storage_manager;
	MidgardCRNamespaceManager* _ns_manager;
	MidgardCRStorageModel** _storage_models;
	gint _storage_models_length1;
	gint __storage_models_size_;
	MidgardCRSchemaModel** _schema_models;
	gint _schema_models_length1;
	gint __schema_models_size_;
	MidgardCRModel** _models;
	gint _models_length1;
	gint __models_size_;
	GSList* _query_slist;
};

struct _MidgardCRSQLStorageModelManagerClass {
	GObjectClass parent_class;
};


GType midgard_cr_config_get_type (void) G_GNUC_CONST;
gboolean midgard_cr_config_read_configuration (MidgardCRConfig* self, const char* name, gboolean user, GError** error);
gboolean midgard_cr_config_read_configuration_at_path (MidgardCRConfig* self, const char* path, GError** error);
gboolean midgard_cr_config_read_data (MidgardCRConfig* self, const char* data, GError** error);
gboolean midgard_cr_config_save_configuration (MidgardCRConfig* self, const char* name, gboolean user, GError** error);
gboolean midgard_cr_config_save_configuration_at_path (MidgardCRConfig* self, const char* path, GError** error);
char** midgard_cr_config_list_configurations (gboolean user, int* result_length1, GError** error);
MidgardCRConfig* midgard_cr_config_copy (MidgardCRConfig* self);
MidgardCRConfig* midgard_cr_config_new (void);
MidgardCRConfig* midgard_cr_config_construct (GType object_type);
const char* midgard_cr_config_get_authtype (MidgardCRConfig* self);
void midgard_cr_config_set_authtype (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_dbname (MidgardCRConfig* self);
void midgard_cr_config_set_dbname (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_dbpass (MidgardCRConfig* self);
void midgard_cr_config_set_dbpass (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_dbtype (MidgardCRConfig* self);
void midgard_cr_config_set_dbtype (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_dbuser (MidgardCRConfig* self);
void midgard_cr_config_set_dbuser (MidgardCRConfig* self, const char* value);
guint midgard_cr_config_get_dbport (MidgardCRConfig* self);
void midgard_cr_config_set_dbport (MidgardCRConfig* self, guint value);
const char* midgard_cr_config_get_host (MidgardCRConfig* self);
void midgard_cr_config_set_host (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_logfilename (MidgardCRConfig* self);
void midgard_cr_config_set_logfilename (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_loglevel (MidgardCRConfig* self);
void midgard_cr_config_set_loglevel (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_midgardpassword (MidgardCRConfig* self);
void midgard_cr_config_set_midgardpassword (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_midgardusername (MidgardCRConfig* self);
void midgard_cr_config_set_midgardusername (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_sharedir (MidgardCRConfig* self);
void midgard_cr_config_set_sharedir (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_vardir (MidgardCRConfig* self);
void midgard_cr_config_set_vardir (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_blobdir (MidgardCRConfig* self);
void midgard_cr_config_set_blobdir (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_cachedir (MidgardCRConfig* self);
void midgard_cr_config_set_cachedir (MidgardCRConfig* self, const char* value);
const char* midgard_cr_config_get_dbdir (MidgardCRConfig* self);
void midgard_cr_config_set_dbdir (MidgardCRConfig* self, const char* value);
gboolean midgard_cr_config_get_tablecreate (MidgardCRConfig* self);
void midgard_cr_config_set_tablecreate (MidgardCRConfig* self, gboolean value);
gboolean midgard_cr_config_get_tableupdate (MidgardCRConfig* self);
void midgard_cr_config_set_tableupdate (MidgardCRConfig* self, gboolean value);
gboolean midgard_cr_config_get_testunit (MidgardCRConfig* self);
void midgard_cr_config_set_testunit (MidgardCRConfig* self, gboolean value);
GQuark midgard_cr_executable_error_quark (void);
GType midgard_cr_executable_get_type (void) G_GNUC_CONST;
void midgard_cr_executable_execute (MidgardCRExecutable* self, GError** error);
GQuark midgard_cr_namespace_manager_error_quark (void);
GType midgard_cr_namespace_manager_get_type (void) G_GNUC_CONST;
gboolean midgard_cr_namespace_manager_create_uri (MidgardCRNamespaceManager* self, const char* uri, const char* name, GError** error);
char** midgard_cr_namespace_manager_list_names (MidgardCRNamespaceManager* self, int* result_length1);
char* midgard_cr_namespace_manager_get_uri_by_name (MidgardCRNamespaceManager* self, const char* name);
char* midgard_cr_namespace_manager_get_name_by_uri (MidgardCRNamespaceManager* self, const char* uri);
gboolean midgard_cr_namespace_manager_name_exists (MidgardCRNamespaceManager* self);
gboolean midgard_cr_namespace_manager_uri_exists (MidgardCRNamespaceManager* self);
GType midgard_cr_profiler_get_type (void) G_GNUC_CONST;
void midgard_cr_profiler_enable (MidgardCRProfiler* self, gboolean toggle);
void midgard_cr_profiler_start (MidgardCRProfiler* self);
void midgard_cr_profiler_end (MidgardCRProfiler* self);
gint midgard_cr_profiler_get_time (MidgardCRProfiler* self);
char* midgard_cr_profiler_get_execution_command (MidgardCRProfiler* self);
GType midgard_cr_query_constraint_simple_get_type (void) G_GNUC_CONST;
MidgardCRQueryConstraintSimple** midgard_cr_query_constraint_simple_list_constraints (MidgardCRQueryConstraintSimple* self, int* result_length1);
GType midgard_cr_query_storage_get_type (void) G_GNUC_CONST;
const char* midgard_cr_query_storage_get_classname (MidgardCRQueryStorage* self);
void midgard_cr_query_storage_set_classname (MidgardCRQueryStorage* self, const char* value);
GType midgard_cr_query_value_holder_get_type (void) G_GNUC_CONST;
GType midgard_cr_query_property_get_type (void) G_GNUC_CONST;
GType midgard_cr_query_constraint_get_type (void) G_GNUC_CONST;
MidgardCRQueryValueHolder* midgard_cr_query_constraint_get_holder (MidgardCRQueryConstraint* self);
void midgard_cr_query_constraint_set_holder (MidgardCRQueryConstraint* self, MidgardCRQueryValueHolder* value);
MidgardCRQueryProperty* midgard_cr_query_constraint_get_property (MidgardCRQueryConstraint* self);
void midgard_cr_query_constraint_set_property (MidgardCRQueryConstraint* self, MidgardCRQueryProperty* value);
MidgardCRQueryStorage* midgard_cr_query_constraint_get_storage (MidgardCRQueryConstraint* self);
void midgard_cr_query_constraint_set_storage (MidgardCRQueryConstraint* self, MidgardCRQueryStorage* value);
const char* midgard_cr_query_constraint_get_operator (MidgardCRQueryConstraint* self);
void midgard_cr_query_constraint_set_operator (MidgardCRQueryConstraint* self, const char* value);
GType midgard_cr_query_constraint_group_get_type (void) G_GNUC_CONST;
char* midgard_cr_query_constraint_group_get_group_type (MidgardCRQueryConstraintGroup* self);
void midgard_cr_query_constraint_group_set_group_type (MidgardCRQueryConstraintGroup* self, const char* name);
void midgard_cr_query_constraint_group_add_constraint (MidgardCRQueryConstraintGroup* self, MidgardCRQueryConstraintSimple* constraint);
const char* midgard_cr_query_constraint_group_get_grouptype (MidgardCRQueryConstraintGroup* self);
void midgard_cr_query_constraint_group_set_grouptype (MidgardCRQueryConstraintGroup* self, const char* value);
void midgard_cr_query_value_holder_get_value (MidgardCRQueryValueHolder* self, GValue* result);
void midgard_cr_query_value_holder_set_value (MidgardCRQueryValueHolder* self, GValue* value);
GType midgard_cr_query_value_get_type (void) G_GNUC_CONST;
MidgardCRQueryValue* midgard_cr_query_value_new (void);
MidgardCRQueryValue* midgard_cr_query_value_construct (GType object_type);
MidgardCRQueryProperty* midgard_cr_query_property_new (void);
MidgardCRQueryProperty* midgard_cr_query_property_construct (GType object_type);
GQuark midgard_cr_validation_error_quark (void);
GType midgard_cr_query_executor_get_type (void) G_GNUC_CONST;
void midgard_cr_query_executor_set_constraint (MidgardCRQueryExecutor* self, MidgardCRQueryConstraintSimple* constraint);
void midgard_cr_query_executor_set_limit (MidgardCRQueryExecutor* self, guint limit);
void midgard_cr_query_executor_set_offset (MidgardCRQueryExecutor* self, guint offset);
void midgard_cr_query_executor_add_order (MidgardCRQueryExecutor* self, MidgardCRQueryProperty* property, const char* type);
guint midgard_cr_query_executor_get_results_count (MidgardCRQueryExecutor* self);
void midgard_cr_query_executor_validate (MidgardCRQueryExecutor* self, GError** error);
GType midgard_cr_storable_get_type (void) G_GNUC_CONST;
GType midgard_cr_query_select_get_type (void) G_GNUC_CONST;
void midgard_cr_query_select_add_join (MidgardCRQuerySelect* self, const char* type, MidgardCRQueryProperty* left_property, MidgardCRQueryProperty* right_property);
MidgardCRStorable** midgard_cr_query_select_list_objects (MidgardCRQuerySelect* self, int* result_length1);
void midgard_cr_query_select_toggle_read_only (MidgardCRQuerySelect* self, gboolean toggle);
GType midgard_cr_query_data_get_type (void) G_GNUC_CONST;
void midgard_cr_query_data_add_join (MidgardCRQueryData* self, const char* type, MidgardCRQueryProperty* left_property, MidgardCRQueryProperty* right_property);
void midgard_cr_query_data_collect_property (MidgardCRQueryData* self, MidgardCRQueryProperty* property, MidgardCRQueryStorage* storage);
void midgard_cr_query_data_list_data (MidgardCRQueryData* self);
GType midgard_cr_model_get_type (void) G_GNUC_CONST;
GType midgard_cr_model_reflector_get_type (void) G_GNUC_CONST;
MidgardCRModel* midgard_cr_model_reflector_get_model (MidgardCRModelReflector* self);
GType midgard_cr_model_property_reflector_get_type (void) G_GNUC_CONST;
char* midgard_cr_model_property_reflector_get_typename (MidgardCRModelPropertyReflector* self);
GType midgard_cr_model_property_reflector_get_gtype (MidgardCRModelPropertyReflector* self);
void midgard_cr_model_property_reflector_get_default_value (MidgardCRModelPropertyReflector* self, GValue* result);
gboolean midgard_cr_model_property_reflector_is_private (MidgardCRModelPropertyReflector* self);
char* midgard_cr_model_property_reflector_get_description (MidgardCRModelPropertyReflector* self);
MidgardCRModel* midgard_cr_model_add_model (MidgardCRModel* self, MidgardCRModel* model);
MidgardCRModel* midgard_cr_model_get_model_by_name (MidgardCRModel* self, const char* name);
MidgardCRModel** midgard_cr_model_list_models (MidgardCRModel* self, int* result_length1);
MidgardCRModelReflector* midgard_cr_model_get_reflector (MidgardCRModel* self);
void midgard_cr_model_is_valid (MidgardCRModel* self, GError** error);
MidgardCRModel* midgard_cr_model_get_parent (MidgardCRModel* self);
void midgard_cr_model_set_parent (MidgardCRModel* self, MidgardCRModel* value);
const char* midgard_cr_model_get_namespace (MidgardCRModel* self);
void midgard_cr_model_set_namespace (MidgardCRModel* self, const char* value);
const char* midgard_cr_model_get_name (MidgardCRModel* self);
void midgard_cr_model_set_name (MidgardCRModel* self, const char* value);
GType midgard_cr_model_property_get_type (void) G_GNUC_CONST;
GType midgard_cr_model_property_get_valuegtype (MidgardCRModelProperty* self);
const char* midgard_cr_model_property_get_valuetypename (MidgardCRModelProperty* self);
void midgard_cr_model_property_set_valuetypename (MidgardCRModelProperty* self, const char* value);
const char* midgard_cr_model_property_get_valuedefault (MidgardCRModelProperty* self);
void midgard_cr_model_property_set_valuedefault (MidgardCRModelProperty* self, const char* value);
const char* midgard_cr_model_property_get_description (MidgardCRModelProperty* self);
void midgard_cr_model_property_set_description (MidgardCRModelProperty* self, const char* value);
gboolean midgard_cr_model_property_get_private (MidgardCRModelProperty* self);
void midgard_cr_model_property_set_private (MidgardCRModelProperty* self, gboolean value);
GType midgard_cr_schema_model_get_type (void) G_GNUC_CONST;
MidgardCRSchemaModel* midgard_cr_schema_model_new (const char* name);
MidgardCRSchemaModel* midgard_cr_schema_model_construct (GType object_type, const char* name);
GType midgard_cr_schema_model_property_get_type (void) G_GNUC_CONST;
MidgardCRSchemaModelProperty* midgard_cr_schema_model_property_new (const char* name, const char* type, const char* dvalue);
MidgardCRSchemaModelProperty* midgard_cr_schema_model_property_construct (GType object_type, const char* name, const char* type, const char* dvalue);
GQuark midgard_cr_schema_builder_error_quark (void);
GType midgard_cr_schema_builder_get_type (void) G_GNUC_CONST;
void midgard_cr_schema_builder_register_model (MidgardCRSchemaBuilder* self, MidgardCRSchemaModel* model, GError** error);
GQuark midgard_cr_storage_manager_error_quark (void);
GQuark midgard_cr_storage_content_manager_error_quark (void);
GType midgard_cr_query_manager_get_type (void) G_GNUC_CONST;
GType midgard_cr_storage_content_manager_get_type (void) G_GNUC_CONST;
GType midgard_cr_storage_executor_get_type (void) G_GNUC_CONST;
GQuark midgard_cr_storage_model_error_quark (void);
GType midgard_cr_storage_model_get_type (void) G_GNUC_CONST;
GType midgard_cr_storage_model_manager_get_type (void) G_GNUC_CONST;
GType midgard_cr_transaction_get_type (void) G_GNUC_CONST;
GType midgard_cr_workspace_storage_get_type (void) G_GNUC_CONST;
GType midgard_cr_storage_workspace_manager_get_type (void) G_GNUC_CONST;
GType midgard_cr_storage_manager_get_type (void) G_GNUC_CONST;
void midgard_cr_schema_builder_register_storage_models (MidgardCRSchemaBuilder* self, MidgardCRStorageManager* manager, GError** error);
MidgardCRStorable* midgard_cr_schema_builder_factory (MidgardCRSchemaBuilder* self, MidgardCRStorageManager* storage, const char* classname, GError** error);
MidgardCRSchemaModel* midgard_cr_schema_builder_get_schema_model (MidgardCRSchemaBuilder* self, const char* classname);
MidgardCRSchemaBuilder* midgard_cr_schema_builder_new (void);
MidgardCRSchemaBuilder* midgard_cr_schema_builder_construct (GType object_type);
GType midgard_cr_timestamp_get_type (void) G_GNUC_CONST;
MidgardCRTimestamp* midgard_cr_timestamp_construct (GType object_type);
GType midgard_cr_metadata_get_type (void) G_GNUC_CONST;
MidgardCRMetadata* midgard_cr_metadata_construct (GType object_type);
const char* midgard_cr_metadata_get_parent (MidgardCRMetadata* self);
guint midgard_cr_metadata_get_action (MidgardCRMetadata* self);
MidgardCRTimestamp* midgard_cr_metadata_get_created (MidgardCRMetadata* self);
MidgardCRTimestamp* midgard_cr_metadata_get_revised (MidgardCRMetadata* self);
GType midgard_cr_schema_object_get_type (void) G_GNUC_CONST;
void midgard_cr_schema_object_set_property_value (MidgardCRSchemaObject* self, const char* name, GValue* value);
void midgard_cr_schema_object_get_property_value (MidgardCRSchemaObject* self, const char* name, GValue* result);
char** midgard_cr_schema_object_list_all_properties (MidgardCRSchemaObject* self, int* result_length1);
MidgardCRSchemaObject* midgard_cr_schema_object_construct (GType object_type);
const char* midgard_cr_schema_object_get_guid (MidgardCRSchemaObject* self);
guint midgard_cr_schema_object_get_id (MidgardCRSchemaObject* self);
MidgardCRMetadata* midgard_cr_schema_object_get_metadata (MidgardCRSchemaObject* self);
GType midgard_cr_db_object_get_type (void) G_GNUC_CONST;
MidgardCRDBObject* midgard_cr_db_object_construct (GType object_type);
GType midgard_cr_sql_storage_manager_get_type (void) G_GNUC_CONST;
MidgardCRSQLStorageManager* midgard_cr_sql_storage_manager_new (const char* name, MidgardCRConfig* config, GError** error);
MidgardCRSQLStorageManager* midgard_cr_sql_storage_manager_construct (GType object_type, const char* name, MidgardCRConfig* config, GError** error);
const char* midgard_cr_sql_storage_manager_get_name (MidgardCRSQLStorageManager* self);
MidgardCRConfig* midgard_cr_sql_storage_manager_get_config (MidgardCRSQLStorageManager* self);
gboolean midgard_cr_transaction_begin (MidgardCRTransaction* self);
gboolean midgard_cr_transaction_rollback (MidgardCRTransaction* self);
gboolean midgard_cr_transaction_get_status (MidgardCRTransaction* self);
const char* midgard_cr_transaction_get_name (MidgardCRTransaction* self);
GType midgard_cr_storage_manager_pool_get_type (void) G_GNUC_CONST;
void midgard_cr_storage_manager_pool_register_manager_type (MidgardCRStorageManagerPool* self, const char* classname);
MidgardCRStorageManager* midgard_cr_storage_manager_pool_create_manager (MidgardCRStorageManagerPool* self, const char* classname, const char* name);
char** midgard_cr_storage_manager_pool_list_managers (MidgardCRStorageManagerPool* self, int* result_length1);
MidgardCRStorageManager* midgard_cr_storage_manager_pool_get_manager_by_name (MidgardCRStorageManagerPool* self, const char* name);
gboolean midgard_cr_storage_manager_open (MidgardCRStorageManager* self, GError** error);
gboolean midgard_cr_storage_manager_close (MidgardCRStorageManager* self, GError** error);
gboolean midgard_cr_storage_manager_initialize_storage (MidgardCRStorageManager* self, GError** error);
MidgardCRStorageManager* midgard_cr_storage_manager_fork (MidgardCRStorageManager* self);
MidgardCRStorageManager* midgard_cr_storage_manager_clone (MidgardCRStorageManager* self);
MidgardCRStorageContentManager* midgard_cr_storage_manager_get_content_manager (MidgardCRStorageManager* self);
MidgardCRStorageModelManager* midgard_cr_storage_manager_get_model_manager (MidgardCRStorageManager* self);
MidgardCRProfiler* midgard_cr_storage_manager_get_profiler (MidgardCRStorageManager* self);
MidgardCRTransaction* midgard_cr_storage_manager_get_transaction (MidgardCRStorageManager* self);
MidgardCRStorageWorkspaceManager* midgard_cr_storage_manager_get_workspace_manager (MidgardCRStorageManager* self);
MidgardCRWorkspaceStorage* midgard_cr_storage_workspace_manager_get_workspace (MidgardCRStorageWorkspaceManager* self);
void midgard_cr_storage_workspace_manager_set_workspace (MidgardCRStorageWorkspaceManager* self, MidgardCRWorkspaceStorage* value);
gboolean midgard_cr_storage_executor_exists (MidgardCRStorageExecutor* self);
void midgard_cr_storage_executor_prepare_create (MidgardCRStorageExecutor* self, GError** error);
void midgard_cr_storage_executor_prepare_update (MidgardCRStorageExecutor* self, GError** error);
void midgard_cr_storage_executor_prepare_save (MidgardCRStorageExecutor* self, GError** error);
void midgard_cr_storage_executor_prepare_remove (MidgardCRStorageExecutor* self, GError** error);
void midgard_cr_storage_executor_prepare_purge (MidgardCRStorageExecutor* self, GError** error);
MidgardCRStorageModel* midgard_cr_storage_model_manager_create_storage_model (MidgardCRStorageModelManager* self, MidgardCRSchemaModel* schema_model, const char* location);
MidgardCRStorageModel** midgard_cr_storage_model_manager_list_storage_models (MidgardCRStorageModelManager* self, int* result_length1);
MidgardCRSchemaModel** midgard_cr_storage_model_manager_list_schema_models (MidgardCRStorageModelManager* self, int* result_length1);
MidgardCRNamespaceManager* midgard_cr_storage_model_manager_get_namespace_manager (MidgardCRStorageModelManager* self);
MidgardCRStorageManager* midgard_cr_storage_model_manager_get_storage_manager (MidgardCRStorageModelManager* self);
MidgardCRStorageManager* midgard_cr_storage_content_manager_get_storage_manager (MidgardCRStorageContentManager* self);
gboolean midgard_cr_storage_content_manager_exists (MidgardCRStorageContentManager* self, MidgardCRStorable* object);
gboolean midgard_cr_storage_content_manager_create (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
gboolean midgard_cr_storage_content_manager_update (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
gboolean midgard_cr_storage_content_manager_save (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
gboolean midgard_cr_storage_content_manager_remove (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
gboolean midgard_cr_storage_content_manager_purge (MidgardCRStorageContentManager* self, MidgardCRStorable* object, GError** error);
MidgardCRQueryManager* midgard_cr_storage_content_manager_get_query_manager (MidgardCRStorageContentManager* self);
GType midgard_cr_storage_model_property_get_type (void) G_GNUC_CONST;
void midgard_cr_storage_model_property_set_primary (MidgardCRStorageModelProperty* self, gboolean toggle);
gboolean midgard_cr_storage_model_property_is_primary (MidgardCRStorageModelProperty* self);
void midgard_cr_storage_model_property_set_index (MidgardCRStorageModelProperty* self, gboolean toggle);
gboolean midgard_cr_storage_model_property_has_index (MidgardCRStorageModelProperty* self);
gboolean midgard_cr_storage_model_property_location_set (MidgardCRStorageModelProperty* self, const char* location);
char* midgard_cr_storage_model_property_location_get (MidgardCRStorageModelProperty* self);
gboolean midgard_cr_storage_model_location_set (MidgardCRStorageModel* self, const char* location, GError** error);
char* midgard_cr_storage_model_location_get (MidgardCRStorageModel* self);
GQuark midgard_cr_workspace_storage_error_quark (void);
const char* midgard_cr_workspace_storage_get_path (MidgardCRWorkspaceStorage* self);
GType midgard_cr_workspace_context_get_type (void) G_GNUC_CONST;
char** midgard_cr_workspace_context_get_workspace_names (MidgardCRWorkspaceContext* self, int* result_length1);
GType midgard_cr_workspace_get_type (void) G_GNUC_CONST;
MidgardCRWorkspace* midgard_cr_workspace_context_get_workspace_by_name (MidgardCRWorkspaceContext* self);
gboolean midgard_cr_workspace_context_has_workspace (MidgardCRWorkspaceContext* self, MidgardCRWorkspace* workspace);
MidgardCRWorkspaceContext* midgard_cr_workspace_context_new (void);
MidgardCRWorkspaceContext* midgard_cr_workspace_context_construct (GType object_type);
MidgardCRWorkspace** midgard_cr_workspace_list_children (MidgardCRWorkspace* self, int* result_length1);
MidgardCRWorkspace* midgard_cr_workspace_get_by_path (MidgardCRWorkspace* self);
MidgardCRWorkspace* midgard_cr_workspace_new (void);
MidgardCRWorkspace* midgard_cr_workspace_construct (GType object_type);
MidgardCRWorkspace* midgard_cr_workspace_get_parent (MidgardCRWorkspace* self);
void midgard_cr_workspace_set_parent (MidgardCRWorkspace* self, MidgardCRWorkspace* value);
MidgardCRWorkspaceContext* midgard_cr_workspace_get_context (MidgardCRWorkspace* self);
GType midgard_cr_sql_workspace_manager_get_type (void) G_GNUC_CONST;
gboolean midgard_cr_sql_workspace_manager_workspace_create (MidgardCRSQLWorkspaceManager* self, MidgardCRWorkspaceStorage* workspace, GError** error);
gboolean midgard_cr_sql_workspace_manager_workspace_exists (MidgardCRSQLWorkspaceManager* self, MidgardCRWorkspaceStorage* workspace, GError** error);
MidgardCRSQLWorkspaceManager* midgard_cr_sql_workspace_manager_new (const char* name, MidgardCRConfig* config);
MidgardCRSQLWorkspaceManager* midgard_cr_sql_workspace_manager_construct (GType object_type, const char* name, MidgardCRConfig* config);
GType midgard_cr_sql_storage_model_manager_get_type (void) G_GNUC_CONST;
MidgardCRSQLStorageModelManager* midgard_cr_sql_storage_model_manager_new (void);
MidgardCRSQLStorageModelManager* midgard_cr_sql_storage_model_manager_construct (GType object_type);


G_END_DECLS

#endif
