/* midgard_key_config.c generated by valac, the Vala compiler
 * generated from midgard_key_config.vala, do not modify */

/* 
 * Copyright (C) 2009 Piotr Pokora <piotrek.pokora@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define MIDGARD_TYPE_KEY_CONFIG (midgard_key_config_get_type ())
#define MIDGARD_KEY_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_TYPE_KEY_CONFIG, MidgardKeyConfig))
#define MIDGARD_KEY_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_TYPE_KEY_CONFIG, MidgardKeyConfigClass))
#define MIDGARD_IS_KEY_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_TYPE_KEY_CONFIG))
#define MIDGARD_IS_KEY_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_TYPE_KEY_CONFIG))
#define MIDGARD_KEY_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_TYPE_KEY_CONFIG, MidgardKeyConfigClass))

typedef struct _MidgardKeyConfig MidgardKeyConfig;
typedef struct _MidgardKeyConfigClass MidgardKeyConfigClass;
typedef struct _MidgardKeyConfigPrivate MidgardKeyConfigPrivate;

#define MIDGARD_TYPE_KEY_CONFIG_CONTEXT (midgard_key_config_context_get_type ())
#define MIDGARD_KEY_CONFIG_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDGARD_TYPE_KEY_CONFIG_CONTEXT, MidgardKeyConfigContext))
#define MIDGARD_KEY_CONFIG_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDGARD_TYPE_KEY_CONFIG_CONTEXT, MidgardKeyConfigContextClass))
#define MIDGARD_IS_KEY_CONFIG_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDGARD_TYPE_KEY_CONFIG_CONTEXT))
#define MIDGARD_IS_KEY_CONFIG_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDGARD_TYPE_KEY_CONFIG_CONTEXT))
#define MIDGARD_KEY_CONFIG_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDGARD_TYPE_KEY_CONFIG_CONTEXT, MidgardKeyConfigContextClass))

typedef struct _MidgardKeyConfigContext MidgardKeyConfigContext;
typedef struct _MidgardKeyConfigContextClass MidgardKeyConfigContextClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MidgardKeyConfig {
	GObject parent_instance;
	MidgardKeyConfigPrivate * priv;
	char* path;
	MidgardKeyConfigContext* context;
};

struct _MidgardKeyConfigClass {
	GObjectClass parent_class;
	void (*set_value) (MidgardKeyConfig* self, const char* group, const char* key, const char* value);
	char* (*get_value) (MidgardKeyConfig* self, const char* group, const char* key);
	void (*set_comment) (MidgardKeyConfig* self, const char* group, const char* key, const char* comment);
	char* (*get_comment) (MidgardKeyConfig* self, const char* group, const char* key);
	char** (*list_groups) (MidgardKeyConfig* self, int* result_length1);
	gboolean (*group_exists) (MidgardKeyConfig* self, const char* name);
	gboolean (*delete_group) (MidgardKeyConfig* self, const char* name);
	gboolean (*store) (MidgardKeyConfig* self);
	gboolean (*load_from_data) (MidgardKeyConfig* self, const char* data);
	char* (*to_data) (MidgardKeyConfig* self);
};


static gpointer midgard_key_config_parent_class = NULL;

GType midgard_key_config_get_type (void);
GType midgard_key_config_context_get_type (void);
enum  {
	MIDGARD_KEY_CONFIG_DUMMY_PROPERTY
};
MidgardKeyConfig* midgard_key_config_construct (GType object_type, MidgardKeyConfigContext* keyctx, const char* path);
void midgard_key_config_set_value (MidgardKeyConfig* self, const char* group, const char* key, const char* value);
static void midgard_key_config_real_set_value (MidgardKeyConfig* self, const char* group, const char* key, const char* value);
char* midgard_key_config_get_value (MidgardKeyConfig* self, const char* group, const char* key);
static char* midgard_key_config_real_get_value (MidgardKeyConfig* self, const char* group, const char* key);
void midgard_key_config_set_comment (MidgardKeyConfig* self, const char* group, const char* key, const char* comment);
static void midgard_key_config_real_set_comment (MidgardKeyConfig* self, const char* group, const char* key, const char* comment);
char* midgard_key_config_get_comment (MidgardKeyConfig* self, const char* group, const char* key);
static char* midgard_key_config_real_get_comment (MidgardKeyConfig* self, const char* group, const char* key);
char** midgard_key_config_list_groups (MidgardKeyConfig* self, int* result_length1);
static char** midgard_key_config_real_list_groups (MidgardKeyConfig* self, int* result_length1);
gboolean midgard_key_config_group_exists (MidgardKeyConfig* self, const char* name);
static gboolean midgard_key_config_real_group_exists (MidgardKeyConfig* self, const char* name);
gboolean midgard_key_config_delete_group (MidgardKeyConfig* self, const char* name);
static gboolean midgard_key_config_real_delete_group (MidgardKeyConfig* self, const char* name);
gboolean midgard_key_config_store (MidgardKeyConfig* self);
static gboolean midgard_key_config_real_store (MidgardKeyConfig* self);
gboolean midgard_key_config_load_from_data (MidgardKeyConfig* self, const char* data);
static gboolean midgard_key_config_real_load_from_data (MidgardKeyConfig* self, const char* data);
char* midgard_key_config_to_data (MidgardKeyConfig* self);
static char* midgard_key_config_real_to_data (MidgardKeyConfig* self);
static void midgard_key_config_finalize (GObject* obj);



static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


MidgardKeyConfig* midgard_key_config_construct (GType object_type, MidgardKeyConfigContext* keyctx, const char* path) {
	MidgardKeyConfig * self;
	MidgardKeyConfigContext* _tmp0_;
	char* _tmp1_;
	g_return_val_if_fail (keyctx != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	self = (MidgardKeyConfig*) g_object_new (object_type, NULL);
	self->context = (_tmp0_ = _g_object_ref0 (keyctx), _g_object_unref0 (self->context), _tmp0_);
	self->path = (_tmp1_ = g_strdup (path), _g_free0 (self->path), _tmp1_);
	return self;
}


static void midgard_key_config_real_set_value (MidgardKeyConfig* self, const char* group, const char* key, const char* value) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (group != NULL);
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
	return;
}


void midgard_key_config_set_value (MidgardKeyConfig* self, const char* group, const char* key, const char* value) {
	MIDGARD_KEY_CONFIG_GET_CLASS (self)->set_value (self, group, key, value);
}


static char* midgard_key_config_real_get_value (MidgardKeyConfig* self, const char* group, const char* key) {
	char* result = NULL;
	char* value;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (group != NULL, NULL);
	g_return_val_if_fail (key != NULL, NULL);
	value = NULL;
	result = value;
	return result;
}


char* midgard_key_config_get_value (MidgardKeyConfig* self, const char* group, const char* key) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->get_value (self, group, key);
}


static void midgard_key_config_real_set_comment (MidgardKeyConfig* self, const char* group, const char* key, const char* comment) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (group != NULL);
	g_return_if_fail (key != NULL);
	g_return_if_fail (comment != NULL);
	return;
}


void midgard_key_config_set_comment (MidgardKeyConfig* self, const char* group, const char* key, const char* comment) {
	MIDGARD_KEY_CONFIG_GET_CLASS (self)->set_comment (self, group, key, comment);
}


static char* midgard_key_config_real_get_comment (MidgardKeyConfig* self, const char* group, const char* key) {
	char* result = NULL;
	char* comment;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (group != NULL, NULL);
	g_return_val_if_fail (key != NULL, NULL);
	comment = NULL;
	result = comment;
	return result;
}


char* midgard_key_config_get_comment (MidgardKeyConfig* self, const char* group, const char* key) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->get_comment (self, group, key);
}


static char** midgard_key_config_real_list_groups (MidgardKeyConfig* self, int* result_length1) {
	char** result = NULL;
	gpointer _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	result = (_tmp0_ = NULL, *result_length1 = 0, _tmp0_);
	return result;
}


char** midgard_key_config_list_groups (MidgardKeyConfig* self, int* result_length1) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->list_groups (self, result_length1);
}


static gboolean midgard_key_config_real_group_exists (MidgardKeyConfig* self, const char* name) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (name != NULL, FALSE);
	result = FALSE;
	return result;
}


gboolean midgard_key_config_group_exists (MidgardKeyConfig* self, const char* name) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->group_exists (self, name);
}


static gboolean midgard_key_config_real_delete_group (MidgardKeyConfig* self, const char* name) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (name != NULL, FALSE);
	result = FALSE;
	return result;
}


gboolean midgard_key_config_delete_group (MidgardKeyConfig* self, const char* name) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->delete_group (self, name);
}


static gboolean midgard_key_config_real_store (MidgardKeyConfig* self) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	result = FALSE;
	return result;
}


gboolean midgard_key_config_store (MidgardKeyConfig* self) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->store (self);
}


static gboolean midgard_key_config_real_load_from_data (MidgardKeyConfig* self, const char* data) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (data != NULL, FALSE);
	result = FALSE;
	return result;
}


gboolean midgard_key_config_load_from_data (MidgardKeyConfig* self, const char* data) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->load_from_data (self, data);
}


static char* midgard_key_config_real_to_data (MidgardKeyConfig* self) {
	char* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = NULL;
	return result;
}


char* midgard_key_config_to_data (MidgardKeyConfig* self) {
	return MIDGARD_KEY_CONFIG_GET_CLASS (self)->to_data (self);
}


static void midgard_key_config_class_init (MidgardKeyConfigClass * klass) {
	midgard_key_config_parent_class = g_type_class_peek_parent (klass);
	MIDGARD_KEY_CONFIG_CLASS (klass)->set_value = midgard_key_config_real_set_value;
	MIDGARD_KEY_CONFIG_CLASS (klass)->get_value = midgard_key_config_real_get_value;
	MIDGARD_KEY_CONFIG_CLASS (klass)->set_comment = midgard_key_config_real_set_comment;
	MIDGARD_KEY_CONFIG_CLASS (klass)->get_comment = midgard_key_config_real_get_comment;
	MIDGARD_KEY_CONFIG_CLASS (klass)->list_groups = midgard_key_config_real_list_groups;
	MIDGARD_KEY_CONFIG_CLASS (klass)->group_exists = midgard_key_config_real_group_exists;
	MIDGARD_KEY_CONFIG_CLASS (klass)->delete_group = midgard_key_config_real_delete_group;
	MIDGARD_KEY_CONFIG_CLASS (klass)->store = midgard_key_config_real_store;
	MIDGARD_KEY_CONFIG_CLASS (klass)->load_from_data = midgard_key_config_real_load_from_data;
	MIDGARD_KEY_CONFIG_CLASS (klass)->to_data = midgard_key_config_real_to_data;
	G_OBJECT_CLASS (klass)->finalize = midgard_key_config_finalize;
}


static void midgard_key_config_instance_init (MidgardKeyConfig * self) {
	self->path = NULL;
}


static void midgard_key_config_finalize (GObject* obj) {
	MidgardKeyConfig * self;
	self = MIDGARD_KEY_CONFIG (obj);
	_g_free0 (self->path);
	_g_object_unref0 (self->context);
	G_OBJECT_CLASS (midgard_key_config_parent_class)->finalize (obj);
}


GType midgard_key_config_get_type (void) {
	static volatile gsize midgard_key_config_type_id__volatile = 0;
	if (g_once_init_enter (&midgard_key_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidgardKeyConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midgard_key_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidgardKeyConfig), 0, (GInstanceInitFunc) midgard_key_config_instance_init, NULL };
		GType midgard_key_config_type_id;
		midgard_key_config_type_id = g_type_register_static (G_TYPE_OBJECT, "MidgardKeyConfig", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&midgard_key_config_type_id__volatile, midgard_key_config_type_id);
	}
	return midgard_key_config_type_id__volatile;
}




